#!/bin/bash

if ! dpkg-query -W -f '${Status}' amulet | grep ^install 1>/dev/null; then
    sudo add-apt-repository ppa:juju/stable -y
    sudo apt-get update
    sudo apt-get install amulet python-requests -y
fi
