#!/bin/bash

template_input = '''
  input {
    file {
        path => "/tmp/noisytest"
        start_position => "beginning"
    }
}
'''

echo $template_input > /etc/logstash/conf.d/input-charm-noise.conf
service logstash restart

for i in {0..2000}; do echo "simulated noise $i times" >> /tmp/noisytest; done
